### PR TITLE
fix: Build csv2arrow, csv2parquet, json2arrow and json2parquet from just one codebase

### PR DESCRIPTION
**Pull request by sacundim**
This tool and its companion [json2parquet](https://github.com/domoritz/json2parquet) really fill an important niche, thank you so much for figuring this out!  I'd been wanting to try and write this, but been daunted by Rust.

I did however look at the repos, noted all the code duplication, and that didn't sit right with me, so I sat down and stared at unfamiliar Rust error messages for a couple of hours to see if I could figure out a way of making the meat of the code more generic and thus build both executables from the same codebase.  And somehow I did manage to get something working!  There's likely a better way of doing this, but hopefully this at lest serves as a working example.

### CODE REVIEW

**Comment by sacundim** [comment]
Ah, I didn't notice at first that there's also a `csv2arrow` and a `json2arrow` repo.  I just went ahead and genericized the output format as well, now the PR builds all four tools from the same codebase.

**Comment by domoritz** [comment]
Thank you for your pull request. I am generally very supportive of this effort to combine the repos. I also noticed that I spend a lot of effort redoing work across repos. However, I think it's nice to have separate crates. Would you have an idea for how we could still have separate crates? One option I could imagine is having a single repo with folders for each crate that then use a common shared library. Thoughts?

**Comment by sacundim** [comment]
@domoritz Not something I have much experience with yet. Your ideas on how to achieve that are likely as good as mine.

I will say that one reason I looked into this is because I'm bundling both csv2parquet and json2parquet into a Docker image, and having the separate crates means double of an already very long build time: [19 minutes in GitHub Actions](https://github.com/sacundim/covid-19-puerto-rico/actions/runs/2880187129) for [a multi-architecture build that cross-compiles both Intel and ARM64](https://github.com/sacundim/covid-19-puerto-rico/tree/master/csv2parquet). Cargo doesn't reuse work within the two same-platform crate compilations; Cargo's docs recommend using [this tool called `sccache`](https://github.com/mozilla/sccache) to improve it, but I tried it, it didn't work for me, and then I noticed its docs say it doesn't work with bin crates.

**Comment by domoritz** [comment]
Can you download the builds from GitHub releases? That would be much faster.

**Comment by domoritz** [comment]
closing since we need a different setup

**Pull request closed without merging**
